"""
Object storage for resume PDFs: any S3-compatible service via boto3, or
./media/ locally.

Production uses Backblaze B2 (10 GB free, no payment card). This module only
speaks the S3 API, so moving to Cloudflare R2, AWS S3 or MinIO is a change of
environment variables, not of code.
"""

import logging
from pathlib import Path

import boto3
from botocore.config import Config
from botocore.exceptions import BotoCoreError, ClientError
from django.conf import settings

logger = logging.getLogger(__name__)


class StorageError(Exception):
    """The storage service could not be reached or refused the request."""

# WHY 15 minutes: long enough to open or download the PDF after clicking, short
# enough that a link pasted into a chat or left in browser history stops
# working soon. A resume is personal data; links should not outlive the visit.
PRESIGNED_URL_EXPIRY_SECONDS = 15 * 60

REQUIRED_STORAGE_SETTINGS = (
    "STORAGE_ENDPOINT",
    "STORAGE_REGION",
    "STORAGE_BUCKET",
    "STORAGE_ACCESS_KEY_ID",
    "STORAGE_SECRET_ACCESS_KEY",
)


def _missing_storage_settings():
    missing = []
    for name in REQUIRED_STORAGE_SETTINGS:
        if not getattr(settings, name, ""):
            missing.append(name)
    return missing


def is_configured():
    return len(_missing_storage_settings()) == 0


def _warn_local_fallback(action):
    # WHY fall back instead of raising: local development and tests should not
    # need a storage account. The warning is loud and names the missing
    # variables so a misconfigured production deploy is obvious in the logs
    # rather than silently writing to a disk that Render wipes on redeploy.
    logger.warning(
        "Object storage is not configured (missing: %s). %s is using the local "
        "directory %s instead. Files stored there do not survive a redeploy.",
        ", ".join(_missing_storage_settings()),
        action,
        settings.MEDIA_ROOT,
    )


def _remove_expect_header(request, **kwargs):
    request.headers.pop("Expect", None)


def _client():
    client = boto3.client(
        "s3",
        endpoint_url=settings.STORAGE_ENDPOINT,
        # The region is part of the signature, so it must match the endpoint
        # (for B2, "us-west-004" goes with s3.us-west-004.backblazeb2.com).
        region_name=settings.STORAGE_REGION,
        aws_access_key_id=settings.STORAGE_ACCESS_KEY_ID,
        aws_secret_access_key=settings.STORAGE_SECRET_ACCESS_KEY,
        config=Config(
            signature_version="s3v4",
            # WHY "when_required": recent boto3 versions add CRC checksum
            # headers to every upload by default. Not every S3-compatible
            # provider accepts them, and a rejected header fails the whole
            # upload. Sending checksums only when an operation demands one
            # keeps uploads working on B2, R2 and MinIO alike.
            request_checksum_calculation="when_required",
            response_checksum_validation="when_required",
            # WHY short timeouts and few retries: gunicorn kills a worker
            # that takes longer than 30 seconds. boto3's defaults (60-second
            # connect timeout, several retries) let a wrong endpoint or a
            # network problem run past that, so the worker died, the user got
            # the host's bare 502 page, and nothing reached our logs. Failing
            # within a few seconds returns a real error and logs the cause.
            connect_timeout=5,
            read_timeout=15,
            retries={"max_attempts": 2, "mode": "standard"},
        ),
    )
    # WHY drop "Expect: 100-continue": botocore adds it to uploads so the
    # server can refuse before the body is sent. Backblaze B2's interim reply
    # confused botocore's HTTP client: one upload failed with "connection was
    # closed" (BadStatusLine on a Strict-Transport-Security header) and another
    # stalled for 16 seconds. Without the header the same upload gets a normal
    # reply in under 2 seconds. The header isn't part of the SigV4 signature,
    # so removing it just before sending is safe.
    client.meta.events.register("before-send.s3", _remove_expect_header)
    return client


def _storage_failure(action, key, exc):
    # Log what's needed to fix the configuration (endpoint, bucket, the
    # service's error) but never the credentials.
    logger.error(
        "Storage %s failed for key %s (endpoint %s, region %s, bucket %s): %s",
        action,
        key,
        settings.STORAGE_ENDPOINT,
        settings.STORAGE_REGION,
        settings.STORAGE_BUCKET,
        exc,
    )
    return StorageError(f"Storage {action} failed: {exc}")


def _local_path(key):
    media_root = Path(settings.MEDIA_ROOT).resolve()
    path = (media_root / key).resolve()
    # WHY check: keys are generated by us today, but if a key ever contained
    # "../" this would write or delete outside the media directory.
    if not path.is_relative_to(media_root):
        raise ValueError(f"Storage key escapes the media directory: {key!r}")
    return path


def upload_file(key, data, content_type="application/pdf"):
    """Store bytes under key. Returns the key."""
    if is_configured():
        try:
            _client().put_object(
                Bucket=settings.STORAGE_BUCKET,
                Key=key,
                Body=data,
                ContentType=content_type,
            )
        except (BotoCoreError, ClientError) as exc:
            raise _storage_failure("upload", key, exc) from exc
        logger.info("Uploaded %s to bucket %s", key, settings.STORAGE_BUCKET)
        return key

    _warn_local_fallback("upload")
    path = _local_path(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    logger.info("Saved %s to %s", key, path)
    return key


def delete_file(key):
    """Delete the object under key. Deleting a key that doesn't exist is not an error."""
    if is_configured():
        try:
            _client().delete_object(Bucket=settings.STORAGE_BUCKET, Key=key)
        except (BotoCoreError, ClientError) as exc:
            raise _storage_failure("delete", key, exc) from exc
        logger.info("Deleted %s from bucket %s", key, settings.STORAGE_BUCKET)
        return

    _warn_local_fallback("delete")
    _local_path(key).unlink(missing_ok=True)


def presigned_url(key, expires_in=PRESIGNED_URL_EXPIRY_SECONDS):
    """
    A short-lived URL for reading the object.

    In local fallback mode this is a plain /media/ URL: it is not signed and
    does not expire, which is acceptable only because it never leaves the
    developer's machine.
    """
    if is_configured():
        # generate_presigned_url signs locally; it makes no network request.
        return _client().generate_presigned_url(
            "get_object",
            Params={"Bucket": settings.STORAGE_BUCKET, "Key": key},
            ExpiresIn=expires_in,
        )

    _warn_local_fallback("presigned_url")
    return settings.MEDIA_URL + key
