"""
Object storage for resume PDFs: Cloudflare R2 via boto3, or ./media/ locally.

R2 speaks the S3 API, so boto3's S3 client works against it unchanged apart
from the endpoint URL.
"""

import logging
from pathlib import Path

import boto3
from django.conf import settings

logger = logging.getLogger(__name__)

# WHY 15 minutes: long enough to open or download the PDF after clicking, short
# enough that a link pasted into a chat or left in browser history stops
# working soon. A resume is personal data; links should not outlive the visit.
PRESIGNED_URL_EXPIRY_SECONDS = 15 * 60

REQUIRED_R2_SETTINGS = ("R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY", "R2_BUCKET", "R2_ENDPOINT")


def _missing_r2_settings():
    missing = []
    for name in REQUIRED_R2_SETTINGS:
        if not getattr(settings, name, ""):
            missing.append(name)
    return missing


def is_r2_configured():
    return len(_missing_r2_settings()) == 0


def _warn_local_fallback(action):
    # WHY fall back instead of raising: local development and tests should not
    # need a Cloudflare account. The warning is loud and names the missing
    # variables so a misconfigured production deploy is obvious in the logs
    # rather than silently writing to a disk that Render wipes on redeploy.
    logger.warning(
        "R2 is not configured (missing: %s). %s is using the local directory %s "
        "instead. Files stored there do not survive a redeploy.",
        ", ".join(_missing_r2_settings()),
        action,
        settings.MEDIA_ROOT,
    )


def _r2_client():
    return boto3.client(
        "s3",
        endpoint_url=settings.R2_ENDPOINT,
        aws_access_key_id=settings.R2_ACCESS_KEY_ID,
        aws_secret_access_key=settings.R2_SECRET_ACCESS_KEY,
        # WHY "auto": R2 has no regions, but boto3 needs one to sign requests.
        # "auto" is the value Cloudflare documents for this.
        region_name="auto",
    )


def _local_path(key):
    media_root = Path(settings.MEDIA_ROOT).resolve()
    path = (media_root / key).resolve()
    # WHY check: keys are generated by us today, but if a key ever contained
    # "../" this would write or delete outside the media directory.
    if not path.is_relative_to(media_root):
        raise ValueError(f"Storage key escapes the media directory: {key!r}")
    return path


def upload_file(key, data, content_type="application/pdf"):
    """Store bytes under key. Returns the key."""
    if is_r2_configured():
        _r2_client().put_object(
            Bucket=settings.R2_BUCKET,
            Key=key,
            Body=data,
            ContentType=content_type,
        )
        logger.info("Uploaded %s to R2 bucket %s", key, settings.R2_BUCKET)
        return key

    _warn_local_fallback("upload")
    path = _local_path(key)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    logger.info("Saved %s to %s", key, path)
    return key


def delete_file(key):
    """Delete the object under key. Deleting a key that doesn't exist is not an error."""
    if is_r2_configured():
        _r2_client().delete_object(Bucket=settings.R2_BUCKET, Key=key)
        logger.info("Deleted %s from R2 bucket %s", key, settings.R2_BUCKET)
        return

    _warn_local_fallback("delete")
    _local_path(key).unlink(missing_ok=True)


def presigned_url(key, expires_in=PRESIGNED_URL_EXPIRY_SECONDS):
    """
    A short-lived URL for reading the object.

    In local fallback mode this is a plain /media/ URL: it is not signed and
    does not expire, which is acceptable only because it never leaves the
    developer's machine.
    """
    if is_r2_configured():
        # generate_presigned_url signs locally; it makes no network request.
        return _r2_client().generate_presigned_url(
            "get_object",
            Params={"Bucket": settings.R2_BUCKET, "Key": key},
            ExpiresIn=expires_in,
        )

    _warn_local_fallback("presigned_url")
    return settings.MEDIA_URL + key
