# Generated by Django 5.2.17 on 2026-10-01 08:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_corpussnapshot'),
        ('resumes', '0002_rename_r2_key_storage_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('jd_text', models.TextField(blank=True)),
                ('plan', models.JSONField(default=list)),
                ('current_question', models.IntegerField(default=0)),
                ('follow_up_asked', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('report', models.JSONField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='analysis.analysis')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('speaker', models.CharField(choices=[('interviewer', 'Interviewer'), ('candidate', 'Candidate')], max_length=20)),
                ('text', models.TextField()),
                ('question_index', models.IntegerField(blank=True, null=True)),
                ('is_follow_up', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('session', 'order'), name='unique_message_order_per_session')],
            },
        ),
    ]
