"""
Skills taxonomy: category -> list of (canonical name, aliases).

Aliases are lowercase and matched with word boundaries by analysis/matcher.py.
Multi-word aliases match across any whitespace, including PDF line breaks.
"""

# WHY: some obvious aliases are deliberately left out because they are ordinary
# English words that show up in almost every JD and would produce false
# positives no matter how good the word-boundary logic is:
#   "rest"    -> "the rest of the team"      (use "restful", "rest api")
#   "express" -> "express your ideas"        (use "express.js", "expressjs")
#   "node"    -> "tree node", "graph node"   (use "node.js", "nodejs")
#   "spring"  -> "spring internship"         (use "spring boot")
#   "next"    -> "next generation platform"  (use "next.js", "nextjs")
# The cost is missing a JD that writes just "Express". That is the better
# failure: a missed match lowers a score slightly, a false match tells the user
# they have a skill gap closed that they don't.
#
# "r", "c" and "go" are kept even though they are risky, because JDs really do
# write "R", "C" and "Go" bare. Word boundaries stop them matching inside
# "react", "c++" or "google", but they cannot stop "Go" the English verb
# ("ready to go live"). That is a known limitation, not a bug in the matcher.

SKILL_TAXONOMY = {
    "languages": [
        ("JavaScript", ["javascript", "js", "es6", "ecmascript"]),
        ("TypeScript", ["typescript", "ts"]),
        ("Python", ["python", "python3", "py"]),
        ("Java", ["java", "core java", "j2ee"]),
        ("C++", ["c++", "cpp"]),
        ("C", ["c"]),
        ("C#", ["c#", "csharp"]),
        ("Go", ["go", "golang"]),
        ("Rust", ["rust"]),
        ("Kotlin", ["kotlin"]),
        ("Swift", ["swift"]),
        ("Ruby", ["ruby"]),
        ("PHP", ["php"]),
        ("Scala", ["scala"]),
        ("R", ["r"]),
        ("Dart", ["dart"]),
        ("SQL", ["sql"]),
        ("HTML", ["html", "html5"]),
        ("CSS", ["css", "css3"]),
        ("Shell Scripting", ["bash", "shell scripting", "shell script"]),
        ("MATLAB", ["matlab"]),
    ],
    "frontend": [
        ("React", ["react", "reactjs", "react.js"]),
        ("Angular", ["angular", "angularjs"]),
        ("Vue.js", ["vue", "vuejs", "vue.js"]),
        ("Next.js", ["next.js", "nextjs"]),
        ("Nuxt.js", ["nuxt", "nuxtjs", "nuxt.js"]),
        ("Svelte", ["svelte", "sveltekit"]),
        ("Redux", ["redux", "redux toolkit", "rtk"]),
        ("React Native", ["react native", "react-native"]),
        ("Flutter", ["flutter"]),
        ("jQuery", ["jquery"]),
        ("Tailwind CSS", ["tailwind", "tailwindcss", "tailwind css"]),
        ("Bootstrap", ["bootstrap"]),
        ("Sass", ["sass", "scss"]),
        ("Material UI", ["material ui", "material-ui", "mui"]),
        ("shadcn/ui", ["shadcn", "shadcn/ui"]),
        ("Webpack", ["webpack"]),
        ("Vite", ["vite"]),
        ("Babel", ["babel"]),
        ("Jest", ["jest"]),
        ("Vitest", ["vitest"]),
        ("React Testing Library", ["react testing library"]),
        ("Cypress", ["cypress"]),
        ("Playwright", ["playwright"]),
        ("Storybook", ["storybook"]),
        ("Three.js", ["three.js", "threejs"]),
        ("D3.js", ["d3", "d3.js"]),
        ("Zustand", ["zustand"]),
        ("React Query", ["react query", "tanstack query"]),
        ("Web Accessibility", ["accessibility", "a11y", "wcag"]),
        ("Responsive Design", ["responsive design", "responsive web design", "mobile-first"]),
        ("Progressive Web Apps", ["pwa", "pwas", "progressive web app", "progressive web apps"]),
        ("Web Performance", ["web vitals", "core web vitals", "lighthouse"]),
    ],
    "backend": [
        ("Node.js", ["node.js", "nodejs", "node js"]),
        ("Express.js", ["express.js", "expressjs"]),
        ("NestJS", ["nestjs", "nest.js"]),
        ("Django", ["django", "drf", "django rest framework"]),
        ("Flask", ["flask"]),
        ("FastAPI", ["fastapi"]),
        ("Spring Boot", ["spring boot", "springboot", "spring framework"]),
        ("Hibernate", ["hibernate"]),
        (".NET", [".net", "dotnet", "asp.net", ".net core"]),
        ("Ruby on Rails", ["rails", "ruby on rails"]),
        ("Laravel", ["laravel"]),
        ("GraphQL", ["graphql"]),
        ("tRPC", ["trpc"]),
        ("gRPC", ["grpc"]),
        ("Prisma", ["prisma"]),
        ("Kafka", ["kafka", "apache kafka"]),
        ("RabbitMQ", ["rabbitmq"]),
        ("Celery", ["celery"]),
        ("WebSockets", ["websocket", "websockets", "socket.io"]),
        ("OAuth", ["oauth", "oauth2", "openid connect"]),
        ("JWT", ["jwt", "json web token", "json web tokens"]),
    ],
    "databases": [
        ("PostgreSQL", ["postgres", "postgresql", "psql"]),
        ("MySQL", ["mysql"]),
        ("MongoDB", ["mongodb", "mongo", "mongoose"]),
        ("Redis", ["redis"]),
        ("SQLite", ["sqlite"]),
        ("Oracle Database", ["oracle db", "oracle database", "pl/sql", "plsql"]),
        ("SQL Server", ["sql server", "mssql", "ms sql"]),
        ("MariaDB", ["mariadb"]),
        ("Cassandra", ["cassandra"]),
        ("DynamoDB", ["dynamodb"]),
        ("Elasticsearch", ["elasticsearch", "elastic search", "opensearch"]),
        ("Firebase", ["firebase", "firestore"]),
        ("Supabase", ["supabase"]),
        ("Neo4j", ["neo4j"]),
        ("Snowflake", ["snowflake"]),
        ("BigQuery", ["bigquery"]),
        ("NoSQL", ["nosql", "no-sql"]),
        ("ORM", ["orm", "object relational mapping", "object-relational mapping"]),
    ],
    "devops": [
        ("Docker", ["docker", "containerization", "containerisation"]),
        ("Kubernetes", ["kubernetes", "k8s"]),
        ("AWS", ["aws", "amazon web services"]),
        ("Azure", ["azure", "microsoft azure"]),
        ("GCP", ["gcp", "google cloud", "google cloud platform"]),
        ("Git", ["git"]),
        ("GitHub", ["github"]),
        ("GitLab", ["gitlab"]),
        ("GitHub Actions", ["github actions"]),
        ("Jenkins", ["jenkins"]),
        ("CI/CD", ["ci/cd", "cicd", "continuous integration", "continuous deployment", "continuous delivery"]),
        ("Terraform", ["terraform"]),
        ("Ansible", ["ansible"]),
        ("Linux", ["linux", "unix"]),
        ("Nginx", ["nginx"]),
        ("Serverless", ["serverless", "aws lambda"]),
        ("Vercel", ["vercel"]),
        ("Netlify", ["netlify"]),
        ("Cloudflare", ["cloudflare"]),
        ("Prometheus", ["prometheus"]),
        ("Grafana", ["grafana"]),
        ("Helm", ["helm"]),
        ("Jira", ["jira"]),
        ("Postman", ["postman"]),
    ],
    "concepts": [
        ("REST APIs", ["restful", "rest api", "rest apis", "rest-api", "restful api", "restful apis"]),
        ("Microservices", ["microservices", "microservice", "micro-services"]),
        ("System Design", ["system design", "high-level design", "low-level design", "hld", "lld"]),
        ("Data Structures & Algorithms", ["data structures", "algorithms", "dsa"]),
        ("OOP", ["oop", "oops", "object-oriented", "object oriented"]),
        ("Design Patterns", ["design patterns", "design pattern", "solid principles"]),
        ("MVC", ["mvc", "model-view-controller"]),
        ("Service-Oriented Architecture", ["soa", "service-oriented architecture", "service oriented architecture"]),
        ("Event-Driven Architecture", ["event-driven", "event driven", "eda"]),
        ("Distributed Systems", ["distributed systems", "distributed system"]),
        ("Scalability", ["scalability", "scalable", "high availability"]),
        ("Caching", ["caching", "cache"]),
        ("Authentication", ["authentication", "authorization", "auth"]),
        ("Web Security", ["web security", "owasp", "xss", "csrf"]),
        ("Unit Testing", ["unit testing", "unit tests", "unit test"]),
        ("TDD", ["tdd", "test-driven development", "test driven development"]),
        ("Agile", ["agile", "scrum", "kanban"]),
        ("SDLC", ["sdlc", "software development life cycle", "software development lifecycle"]),
        ("Machine Learning", ["machine learning", "ml", "deep learning"]),
        ("Artificial Intelligence", ["ai", "artificial intelligence", "generative ai", "genai", "llm", "llms"]),
        ("Cloud Computing", ["cloud computing", "cloud-based", "cloud based", "cloud-native", "cloud native"]),
        ("Operating Systems", ["operating systems", "operating system"]),
        ("Computer Networks", ["computer networks", "computer networking", "tcp/ip"]),
        ("DBMS", ["dbms", "database management", "database design"]),
        ("Concurrency", ["concurrency", "multithreading", "multi-threading"]),
        ("Performance Optimization", ["performance optimization", "performance optimisation", "performance tuning"]),
        ("Version Control", ["version control"]),
        ("Code Review", ["code review", "code reviews"]),
        ("Debugging", ["debugging"]),
        ("Problem Solving", ["problem solving", "problem-solving"]),
    ],
}

CATEGORY_LABELS = {
    "languages": "Languages",
    "frontend": "Frontend",
    "backend": "Backend",
    "databases": "Databases",
    "devops": "DevOps & Tools",
    "concepts": "Concepts",
}
